### ISSUE TITLE
Mini icon overlay options

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/Profilist#21]
Create stack of toolbar button so I can add mini icons for edit/set default/delete and other options.

![mockup toggle options](http://img.photobucket.com/albums/v135/noitidart/mockup-mini_zpsd42b5b20.png)

so on hover it shows those set of buttons. the aurora one is toggled on (colors up) so when launched from click on regular label it willl startup in aurora.

green bullet means its the selected default profile thats vis even on non-hover. the gray bullet means you can toggle it to be the default profile, if done then the green one fades out and makes the clicked on one green. the plug is to launch it in safe safe mode (non-toggle button, just click and launch). pencil to edit. minus to delete profile.

**Comment by yusf** [comment]
Sweet.

**Comment by Noitidart** [comment]
Thanks @yusf for sharing that comment/feedback :)

**Comment by yusf** [comment]
@Noitidart Keep it up! :100:

**Comment by Noitidart** [comment]
Landed somewhere in v3.0a - https://github.com/Noitidart/Profilist/tree/v3.0a

**Comment by Noitidart** [comment]
Hey @yusf  please try out the beta I uploaded to AMO. It's working pretty good. I'm just trying to solve an icky e10s bug.
