### ISSUE TITLE
Search in new Tab doesn't load page

### ISSUE THREAD

**Issue by RealRaven2000** [Noitidart/Profilist#28]
Profilist 1.2 - Fx 35.0 beta
When "classic search" is configured and it is set up to open search results in a new tab then searching from the search bar will
- open a new tab with the correct search filled in the address bar

however, the tab will *not* load automatically. I have to go to the Address bar and hit return to request the page. Disabling Profilist fixes the problem. List of user defined settings:
browser.search.showOneOffButtons = false
browser.search.openintab = true
browser.search.selectedEngine = 'Google Verbatim'
browser.search.defaultenginename = 'Google Verbatim'
browser.search.hiddenOneOffs = ''
browser.search.useDBForOrder = true
services.sync.prefs.sync.browser.search.selectedEngine = true
browser.search.isUS = false

**Comment by Noitidart** [comment]
Thanks for the report. This is very interesting. Can you please provide a screen shot.

**Comment by RealRaven2000** [comment]
Strangely I have re-enabled Profilist (even restarted) and now cannot reproduce the behavior. I also did some Thunderbird debugging around the period when this happened, but even with this cannot currently reproduce it. I suggest to set the bug to INVALID for now.

**Comment by Noitidart** [comment]
Thanks for that note. I'll do that please deifniely let me know if you find a connection. I can't imagine it would so I had asked for more info. Thanks @RealRaven2000 !

**Comment by RealRaven2000** [comment]
no problem!

The problem "surfaced" over the X-mas holidays and was driving me nuts. temporarily 
disabling profilist (which may have been the very last add-on I installed) somehow 
seemed to fix it. If it happens again I will pay closer attention to the browser 
console output - IIRC there was nothing conclusive in there.

Axel

-- 
*Axel <mailto:axel.grude@gmail.com>*
Software Developer
Thunderbird Add-ons Developer (QuickFolders, quickFilters, QuickPasswords, Zombie 
Keys, SmartTemplate4)
AMO Editor Get Thunderbird!
