### ISSUE TITLE
Profile manager is shown after clicking a profile

### ISSUE THREAD

**Issue by leromarinvit** [Noitidart/Profilist#29]
When I click a profile, sometimes the profile manager is shown instead of directly launching a new instance with the selected profile. To get to the desired profile, I have to manually select it and de-select "Use the selected profile at startup without asking" - which then causes the profile manager to show up the next time I start Firefox from the launcher, where I have to select the default profile again.

OS: Fedora 21
Firefox 36 installed from repository
Profilist 1.2 from addons.mozilla.org

**Comment by Noitidart** [comment]
Thanks for the report I'll look into this :)

**Comment by Noitidart** [comment]
What OS were you using?
Did the profile manager used to show on launch of a profile before you installed profilist?

**Comment by leromarinvit** [comment]
I'm using Linux (Fedora 21). The profile manager behaves normally apart from being shown when switching profiles with profilist.

**Comment by Noitidart** [comment]
When the profile manager shows next time did you try checking the box that says "Use the selected profile without asking on startup"?

**Comment by leromarinvit** [comment]
I tried both ways, the profile manager behaves exactly as if I started it manually with -profilemanager. I can select which profile is started. If I select the checkbox, that profile will be used as default the next time I start Firefox, and if I don't check it, the profile manager will show up on startup until I select a new default profile.

**Comment by Noitidart** [comment]
Wow that's weird. Ok can you please do this:

1. Go to `/home/noit/.mozilla/firefox/profiles.ini` then paste that here
2. Exit all firefoxes, run profile manager, check the box to use selected profile every time, then pick a profile
3. Copy paste the profiles.ini again here
4. Start a profile from the profilist menu
5. copy paste the profiles.ini again here

Lots of copy pasting :P but this will help us figure it out

**Comment by leromarinvit** [comment]
I found the reason - I had a unicode character (ö) in one of the profile names (not in the folder name, just the name in profiles.ini). I renamed the profile, and that seems to have fixed the problem.

**Comment by Noitidart** [comment]
Oh wow very interesting, I thought it was safe to use any character for a profile name. Thanks for that heads up I'll look into that.
