### ISSUE TITLE
Webextension status?

### ISSUE THREAD

**Issue by Radagast** [Noitidart/Profilist#45]
Hi. Just wondering about the current status of the Webextension (Linux) Seems v5 has support, is there something we can try?

**Comment by Noitidart** [comment]
Hi there,
Profilist v5 isn't yet ready. I was doing hybrid webext but then Mozilla said hybrid webext will also not be allowed. So I am now trying pure Webext. Thanks so much for being a user and asking me about this!

**Comment by Oni-Shadow** [comment]
Hi there, 
I am using FF nightly and profilist just got disabled because it is not compatible with multiprocess (electrolysis, E10) functions. Is there any plan on supporting it ?

**Comment by Noitidart** [comment]
I just uploaded v1.2.2 which adds the multiprocess flag. It should be approved soon.

**Comment by Oni-Shadow** [comment]
Brilliant, cheers !

**Comment by Noitidart** [comment]
Thank you Oni and Radagast for this note. Profilist v1.2.2 is approved and out with this fix. :)

**Comment by Oni-Shadow** [comment]
No problem, however eversince we got our favorite addon back, I cannot choose a profile anymore : when I hover my profile name, it doesn't show the remaining profiles.
firefox 55 on ubuntu devel

**Comment by Noitidart** [comment]
Thanks so much Oni-shadow for mentioning this is if your favorite addon!!

That is odd, I will try to look into it.

**Comment by Noitidart** [comment]
@Oni-Shadow - in the webextension version, I am not able to inlay into that main menu, so the it opens in a new tab. Is this ok?

**Comment by Oni-Shadow** [comment]
Sorry for the delay. Yeah, that would do it :) 
However, since the hamburger menu will eventually disappear, you will have to think at another position/way for your addon

**Comment by Oni-Shadow** [comment]
So yeah, the latest nightly builds have got rid of the old menu, using a list now, and your extension button do not appear anymore ; it is not possible to swhich profiles

**Comment by Noitidart** [comment]
Crap :(

I am looking for collaborators to hopefully help with this. Any electron folk out there that want to collaborate.
