### ISSUE TITLE
When go to customize without having opened menu panel, "Profiles Loading..." hangs

### ISSUE THREAD

**Issue by yajd** [Noitidart/Profilist#5]
>As part of my customizing the browser, I removed the hamburger menu button from the nav bar. I enter the Customize Toolbar menu by right-clicking the toolbar and selecting Customize. When you do this, the overlay created by your addon is greyed out, and doesn't work. Using the hamburger menu and it works. You can try that yourself. Possibly you could open a new issue for that.

@grbradt can you please help me understand this.

I tried hard but I can't figure out how to remove the hamburger menu button from navbar. In customize mode/tab the overlay should be greyed out.

**Comment by Noitidart** [comment]
Ok finally fixed!
